name: github-snake

on:
  schedule:
    - cron: '0 * * * *'   # каждый час
  workflow_dispatch:      # запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: p3lim/github-snake-action@main
        with:
          output: output/snake.svg
